#ifndef ITEM_BATTLE_EFFECTS_H
#define ITEM_BATTLE_EFFECTS_H

enum item_effects
{
      ITEM_EFFECT_NOEFFECT , //0x0
      ITEM_EFFECT_ORANBERRY, //0x1
      ITEM_EFFECT_CHERIBERRY , //0x2
      ITEM_EFFECT_CHESTOBERRY , //0x3
      ITEM_EFFECT_PECHABERRY , //0x4
      ITEM_EFFECT_RAWSTBERRY , //0x5
      ITEM_EFFECT_ASPEARBERRY , //0x6
      ITEM_EFFECT_LEPPABERRY , //0x7
      ITEM_EFFECT_PERSIMBERRY , //0x8
      ITEM_EFFECT_LUMBERRY , //0x9
      ITEM_EFFECT_FIGYBERRY , //0xA
      ITEM_EFFECT_WIKIBERRY , //0xB
      ITEM_EFFECT_MAGOBERRY , //0xC
      ITEM_EFFECT_AGUAVBERRY , //0xD
      ITEM_EFFECT_IAPAPABERRY , //0xE
      ITEM_EFFECT_LIECHIBERRY , //0xF
      ITEM_EFFECT_GANLONBERRY , //0x10
      ITEM_EFFECT_SALACBERRY , //0x11
      ITEM_EFFECT_PETAYABERRY , //0x12
      ITEM_EFFECT_APICOTBERRY , //0x13
      ITEM_EFFECT_LANSATBERRY , //0x14
      ITEM_EFFECT_STARFBERRY , //0x15
      ITEM_EFFECT_BRIGHTPOWDER , //0x16
      ITEM_EFFECT_WHITEHERB , //0x17
      ITEM_EFFECT_MACHOBRACE , //0x18
      ITEM_EFFECT_EXPSHARE , //0x19
      ITEM_EFFECT_QUICKCLAW , //0x1A
      ITEM_EFFECT_SOOTHEBELL , //0x1B
      ITEM_EFFECT_MENTALHERB , //0x1C
      ITEM_EFFECT_CHOICEBAND , //0x1D
      ITEM_EFFECT_KINGSROCK , //0x1E
      ITEM_EFFECT_SILVERPOWDER , //0x1F
      ITEM_EFFECT_AMULETCOIN , //0x20
      ITEM_EFFECT_CLENSEATAG , //0x21
      ITEM_EFFECT_SOULDEW , //0x22
      ITEM_EFFECT_DEEPSEATOOTH , //0x23
      ITEM_EFFECT_DEEPSEASCALE , //0x24
      ITEM_EFFECT_SMOKEBALL , //0x25
      ITEM_EFFECT_EVERSTONE , //0x26
      ITEM_EFFECT_FOCUSBAND , //0x27
      ITEM_EFFECT_LUCKYEGG , //0x28
      ITEM_EFFECT_SCOPELENS , //0x29
      ITEM_EFFECT_METALCOAT , //0x2A
      ITEM_EFFECT_LEFTOVERS , //0x2B
      ITEM_EFFECT_DRAGONSCALE , //0x2C
      ITEM_EFFECT_LIGHTBALL , //0x2D
      ITEM_EFFECT_SOFTSAND , //0x2E
      ITEM_EFFECT_HARDSTONE , //0x2F
      ITEM_EFFECT_MIRACLESEED , //0x30
      ITEM_EFFECT_BLACKGLASSES , //0x31
      ITEM_EFFECT_BLACKBELT , //0x32
      ITEM_EFFECT_MAGNET , //0x33
      ITEM_EFFECT_MYSTICWATER , //0x34
      ITEM_EFFECT_SHARPBEAK , //0x35
      ITEM_EFFECT_POISONBARB , //0x36
      ITEM_EFFECT_NEVERMELTICE , //0x37
      ITEM_EFFECT_SPELLTAG , //0x38
      ITEM_EFFECT_TWISTEDSPOON , //0x39
      ITEM_EFFECT_CHARCOAL , //0x3A
      ITEM_EFFECT_DRAGONFANG , //0x3B
      ITEM_EFFECT_SILKSCARF , //0x3C
      ITEM_EFFECT_UPGRADE , //0x3D
      ITEM_EFFECT_SHELLBELL , //0x3E
      ITEM_EFFECT_LUCKYPUNCH , //0x3F
      ITEM_EFFECT_METALPOWDER , //0x40
      ITEM_EFFECT_THICKCLUB , //0x41
      ITEM_EFFECT_STICK , //0x42
      ITEM_EFFECT_CHOICESPECS = 0x47,
      ITEM_EFFECT_ADAMANTORB , //0x48
      ITEM_EFFECT_GRISEOUSORB , //0x49
      ITEM_EFFECT_LIFEORB , //0x4A
      ITEM_EFFECT_LUSTROUSORB , //0x4B
      ITEM_EFFECT_EVIOLITE , //0x4C
      ITEM_EFFECT_ASSAULTVEST , //0x4D
      ITEM_EFFECT_MUSCLEBAND , //0x4E
      ITEM_EFFECT_WISEGLASSES , //0x4F
      ITEM_EFFECT_PINKRIBBON , //0x50
      ITEM_EFFECT_RINGTARGET = 0x54,
      ITEM_EFFECT_EXPERTBELT , //0x55
      ITEM_EFFECT_WIDELENS  = 0x68,
      ITEM_EFFECT_ZOOMLENS , //0x69
      ITEM_EFFECT_FOCUSSASH , //0x6A
      ITEM_EFFECT_SAFETYGOOGLES , //0x6B
      ITEM_EFFECT_CHOICESCARF , //0x6C
      ITEM_EFFECT_LAGGINGTAIL , //0x6D
      ITEM_EFFECT_FLOATSTONE , //0x6E
      ITEM_EFFECT_METRONOME , //0x6F
      ITEM_EFFECT_IRONBALL , //0x70
      ITEM_EFFECT_AIRBALLOON , //0x71
      ITEM_EFFECT_HEATROCK , //0x72
      ITEM_EFFECT_DAMPROCK , //0x73
      ITEM_EFFECT_SMOOTHROCK , //0x74
      ITEM_EFFECT_ICYROCK , //0x75
      ITEM_EFFECT_SITRUSBERRY , //0x76
      ITEM_EFFECT_BLACKSLUDGE , //0x77
      ITEM_EFFECT_STICKYBARB , //0x78
      ITEM_EFFECT_FLAMEORB , //0x79
      ITEM_EFFECT_TOXICORB , //0x7A
      ITEM_EFFECT_WEAKNESSPOLICY , //0x7B
      ITEM_EFFECT_EJECTBUTTON , //0x7C
      ITEM_EFFECT_REDCARD , //0x7D
      ITEM_EFFECT_ROCKYHELMET , //0x7E
      ITEM_EFFECT_LIGHTCLAY , //0x7F
      ITEM_EFFECT_DESTINYKNOT , //0x80
      ITEM_EFFECT_LUMINOUSMOSS , //0x81
      ITEM_EFFECT_CELLBATTERY , //0x82
      ITEM_EFFECT_SNOWBALL , //0x83
      ITEM_EFFECT_ABSORBBULB , //0x84
      ITEM_EFFECT_QUICKPOWDER , //0x85
      ITEM_EFFECT_BIGROOT , //0x86
      ITEM_EFFECT_BINDINGBAND , //0x87
      ITEM_EFFECT_GRIPCLAW , //0x88
      ITEM_EFFECT_CUSTAPBERRY , //0x89
      ITEM_EFFECT_POWERHERB , //0x8A
      ITEM_EFFECT_MEGASTONE , //0x8B
      ITEM_EFFECT_DRIVES , //0x8C
      ITEM_EFFECT_PRIMALORB , //0x8D
      ITEM_EFFECT_SHEDSHELL , //0x8E
      ITEM_EFFECT_GEM , //0x8F //the extra is the type it boosts
      ITEM_EFFECT_DAM_REDUX_BERRY , //0x90 //the extra is the type it resists
      ITEM_EFFECT_PLATES , //0x91
      ITEM_EFFECT_MEMORIES, //0x92
      ITEM_EFFECT_TERRAINEXPANDER, //0x93
      ITEM_EFFECT_PROTECTIVEPADS, //0x94 moves dont make contact
      ITEM_EFFECT_ELECTRICSEED, //0x95
      ITEM_EFFECT_GRASSYSEED, //0x96
      ITEM_EFFECT_MISTYSEED, //0x97
      ITEM_EFFECT_PSYCHICSEED, //0x98
};

#endif /* ITEM_BATTLE_EFFECTS_H_H */
